### ISSUE TITLE
Running get-aoc-input.rs doesn't work

### ISSUE THREAD

**Issue by MikeWallaceDev** [ChristopherBiscardi/advent-of-code#17]
When trying to run the "just create day-01" command I got an error stating : 

```
/usr/bin/env: ‘cargo +nightly -Zscript’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```
Indeed, changing the line to 
```
#!/usr/bin/env -S cargo +nightly -Zscript 
```
allowed it to work on my system.

**Comment by ChristopherBiscardi** [comment]
what operating system are you on? Some kind of linux is my guess from the error message.

This is definitely a drawback of the current approach at the moment while cargo-script is in nightly. I'm not sure how to address the issue in a cross-platform way at the moment. Perhaps just documenting it would be enough for now.

**Comment by Paxol** [comment]
Same issue here on arch linux, the proposed solution fixed the problem! Ty

**Comment by nascentt** [comment]
@MikeWallaceDev  is there nowhere to download Focus Gallery Share anymore?  No longer exists on the Play Store. It was invaluable.

**Comment by alycda** [comment]
updated for 2024/nightly: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#script

**Comment by ChristopherBiscardi** [comment]
I've updated the 2024 scripts so going to close this. Happy to make further adjustments if anyone runs into issues.
