### ISSUE TITLE
Remove input text files or at least contents

### ISSUE THREAD

**Issue by Arevjensen** [ChristopherBiscardi/advent-of-code#18]
https://www.reddit.com/r/adventofcode/wiki/faqs/copyright/inputs

**Comment by ChristopherBiscardi** [comment]
This note was added to a subreddit more than halfway through the event this year. I've already addressed the current situation in [a related PR](https://github.com/ChristopherBiscardi/advent-of-code/pull/10).

To be clear, I do plan to do something else next year and remove the files after the event when I have time/not add them in the future but my current workflow requires working across multiple computers and I'm going to finish the current year as-is.
