### ISSUE TITLE
Please remove inputs from the repository

### ISSUE THREAD

**Issue by EldoranDev** [ChristopherBiscardi/advent-of-code#21]
Hi,

Nice repository and great learning materials, while browsing the Repository I saw that you're including the AoC inputs in the code.

It is explicitly asked not to do this by the the creator [here](https://adventofcode.com/2023/about#:~:text=Can%20I%20copy,it%20something%20similar.).

Best Regards

**Comment by ChristopherBiscardi** [comment]
I've already addressed this in multiple issues and PRs. Please search before creating additional ones.
