### ISSUE TITLE
Day 20. Variable equels 0

### ISSUE THREAD

**Issue by heyyyoyy** [ChristopherBiscardi/advent-of-code#3]
Hi, it looks like a bug 
https://github.com/ChristopherBiscardi/advent-of-code/blob/a932c0247756e08ce8fc13f6059d9191f798a0d3/2022/rust/day-20/src/lib.rs#L41
because in the example if you output line by line, then -2 will be at the beginning of the list after five iterations, in the example it is at the end
```
3 moves between 0 and 4:
1, 2, -2, -3, 0, 3, 4

-2 moves between 4 and 1:
1, 2, -3, 0, 3, 4, -2
```
if you add a check for 0 in the `added` variable and insert `current` at the end of the list, then everything will work too and the output from the example will match

**Comment by ChristopherBiscardi** [comment]
have you observed a problem with the program producing the wrong answer to the day 20 question? or is it a display issue you're reporting because the displayed position doesn't match the example's output?

**Comment by heyyyoyy** [comment]
@ChristopherBiscardi it’s problem only for display, answer is correct
